'use strict';

module.exports = {
  action: {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    NAV_CREATE_RACE: 'NAV_CREATE_RACE',
    NAV_CREATED_RACES: 'NAV_CREATED_RACES',
    NAV_SUMMARY: 'NAV_SUMMARY',
    NAV_RACE: 'NAV_RACE',
    CENTER_MAP: 'CENTER_MAP',
    ADD_WAYPOINT: 'ADD_WAYPOINT',
    PUBLISH_RACE: 'PUBLISH_RACE',
    CHECK_IN: 'CHECK_IN',
    ENABLE_CHECK_IN: 'ENABLE_CHECK_IN',
    TIMER_START: 'TIMER_START',
    TIMER_FINISH: 'TIMER_FINISH',
    START_RACE: 'START_RACE',
    FINISH_RACE: 'FINISH_RACE',
    CANCEL_RACE: 'CANCEL_RACE',
    LOCATION_CHANGE: 'LOCATION_CHANGE',
    CLEAR_FORM: 'CLEAR_FORM'
  }
};

